version: '3.9'
services:
  appm:
    container_name: appm
    image: localhost:5000/appm-ms
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    links:
      - monguito
    networks:
      - mired
    
  monguito:
    container_name: monguito
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mired
    
networks:
  mired:
    driver: bridge
volumes:
  mongo-data: